#!/bin/bash

if command -v python3 > /dev/null; then
    python3 -m nunif.cli.waifu2x $*
elif command -v python > /dev/null; then
    python -m nunif.cli.waifu2x $*
else
    echo "error: Could not find python3/python command"
    exit -1
fi

