#!/bin/bash -e

OUTPUT_DIR=./models/swin_unet_v3_1x/
DATA_DIR=./data/waifu2x/
ADDITIONAL_DATA_DIR=./data/waifu2x/gen_screenmain
#ADDITIONAL_DATA_DIR=
# random
SEED=-1

ARCH="waifu2x.swin_unet_v3_1x"
DA_OPTION="--da-grayscale-p 0.01"
OPTIONS="--arch ${ARCH} --optimizer adamw_fused --scheduler cosine_wd --update-criterion loss --seed ${SEED} --data-dir ${DATA_DIR} --model-dir ${OUTPUT_DIR} --drop-last  --eval-step 2 --num-workers 8"
if [ ! -z ${ADDITIONAL_DATA_DIR} ]; then
    # ${ADDITIONAL_DATA_DIR} directory contains 0.1M synthetic data samples
    # generated by waifu2x/training/dot_generator.py and waifu2x/training/screentone_generator.py.
    OPTIONS="${OPTIONS} --additional-data-dir ${ADDITIONAL_DATA_DIR} --additional-data-dir-p 0.01 --hard-example none"
fi

OPTIONS="${OPTIONS} ${DA_OPTION} --ignore-nan "
OVERRIDE=""

# first train --noise-level 1
LOSS="--loss dctirm"

echo "***** ${ARCH} *****"

# *** noise 0

# train

STEP_OPTION="--size 80 --batch-size 16 --num-samples 50000 --max-epoch 60  --learning-rate-cycles 1 --optimizer adamw_schedulefree --learning-rate 0.00005 --warmup-epoch 1"

DEBUG=1 python train.py waifu2x --method noise --noise-level 3 ${OPTIONS} ${STEP_OPTION} ${LOSS} --checkpoint-file ${OUTPUT_DIR}/noise3.0.pth
cp ${OUTPUT_DIR}/noise3.pth ${OUTPUT_DIR}/noise3.1.pth

DEBUG=1 python train.py waifu2x --method noise --noise-level 2 ${OPTIONS} ${STEP_OPTION} ${LOSS} --checkpoint-file ${OUTPUT_DIR}/noise2.0.pth
cp ${OUTPUT_DIR}/noise2.pth ${OUTPUT_DIR}/noise2.1.pth

DEBUG=1 python train.py waifu2x --method noise --noise-level 1 ${OPTIONS} ${STEP_OPTION} ${LOSS} --checkpoint-file ${OUTPUT_DIR}/noise1.0.pth
cp ${OUTPUT_DIR}/noise1.pth ${OUTPUT_DIR}/noise1.1.pth

DEBUG=1 python train.py waifu2x --method noise --noise-level 0 ${OPTIONS} ${STEP_OPTION} ${LOSS} --checkpoint-file ${OUTPUT_DIR}/noise0.0.pth
cp ${OUTPUT_DIR}/noise0.pth ${OUTPUT_DIR}/noise0.1.pth
